project_id = "wvdrsofehwiopbkzrqit"

[functions.ai-search]
verify_jwt = false

[functions.import-products]
verify_jwt = false

[functions.import-products-excel]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.enrich-product]
verify_jwt = false