project_id = "wvdrsofehwiopbkzrqit"

[functions.ai-search]
verify_jwt = false

[functions.submit-po-quote]
verify_jwt = false

[functions.import-products]
verify_jwt = false

[functions.import-products-excel]
verify_jwt = false

[functions.update-products-excel]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.enrich-product]
verify_jwt = false

[functions.update-products-pdf]
verify_jwt = false

[functions.fix-product-stock]
verify_jwt = false

[functions.fix-maggi-stock]
verify_jwt = false

[functions.manage-pos-user]
verify_jwt = false

[functions.create-guest-order]
verify_jwt = false